### ISSUE TITLE
Readme has wrong repository name

### ISSUE THREAD

**Issue by snowe2010** [caarlos0/zsh-git-sync#12]
this repository doesn't allow cloning with ssh.

**Comment by snowe2010** [comment]
nvm. something is broken with my zgen install. I had attempted to verify by visiting the github page, but I wasn't logged in, so it appeared that the repo didn't allow cloning with ssh (which I didn't even think was possible and it appears I was right). Ignore me.

**Comment by caarlos0** [comment]
fixed, thanks
